@FieldsAreNonnullByDefault
@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package codechicken.multipart.minecraft;

import net.covers1624.quack.annotation.FieldsAreNonnullByDefault;
import net.covers1624.quack.annotation.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
